name: Build Wazuh Packages - DEB|RPM - amd64 and i386
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Wazuh branch used while building a package'
        required: false
        default: master
      target:
        type: choice
        description: 'Manager or agent package'
        required: true
        options: 
          - manager
          - agent
      arch:
        type: choice
        description: 'Architecture of the package [amd64, i386, arm64, armhf, ppc64]'
        required: true
        options: 
          - amd64
          - i386
          - arm64
          - armhf
          - ppc64
      package-format:
        type: choice
        description: 'Package format [deb, rpm]'
        required: true
        options: 
          - deb
          - rpm

  workflow_call:

jobs:
  Build-packages-amd64: 
    # The host should always be linux
    runs-on: ubuntu-22.04
    name: Build ${{ github.event.inputs.package }} wazuh-${{ github.event.inputs.target }} on ${{ github.event.inputs.arch }}

    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - uses: actions/checkout@v4
        
      - name: Set tag and container name
        run: |
          VERSION=$(sed 's/^v\([0-9]*\.[0-9]*\.[0-9]*\)/\1/' $GITHUB_WORKSPACE/src/VERSION)
          if [ "${{ github.event.inputs.branch }}" == "master" ]; then echo "TAG=$VERSION" >> $GITHUB_ENV;
          else echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV; fi
          echo "CONTAINER_NAME=${{ github.event.inputs.package-format }}_${{ github.event.inputs.target }}_builder_${{ github.event.inputs.arch }}" >> $GITHUB_ENV

      - name: Download docker image for package building
        run: |
          bash $GITHUB_WORKSPACE/.github/actions/ghcr-pull-and-push/pull_image_from_ghcr.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.actor}} $CONTAINER_NAME ${{ env.TAG }}

      - name: Build ${{ github.event.inputs.package }} wazuh-${{ github.event.inputs.target }} on ${{ github.event.inputs.arch }}
        working-directory: /packages
        run: |
          REVISION=$( echo ${{ github.head_ref }} | sed 's/-/./g; s/\//./g' )
          bash generate_package.sh -b ${{ github.event.inputs.branch }} -j $(nproc)-t ${{ github.event.inputs.target }} -s /tmp -a ${{ github.event.inputs.arch }} --dont-build-docker --tag ${{ env.TAG }} -r $REVISION --package-format ${{ github.event.inputs.package-format }}

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_SECRET_KEY }}
          aws-region: us-east-1

      - name: Get secrets by name
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            WPK_PRIVATE_KEY,${{ secrets.CI_AWS_WPK_PRIVATE_KEY_SECRET_NAME }}
            WPK_CERT,${{ secrets.CI_AWS_WPK_CERT_SECRET_NAME }}

      - name: Upload package to S3
        run: |
          aws s3 cp /tmp/*${{ github.event.inputs.target }}* s3://packages-dev.internal.wazuh.com/development/wazuh/
